export const GET_SOURCES = 'GET_SOURCES'
export const GET_SOURCES_SUCCESS = 'GET_SOURCES_SUCCESS'
export const GET_SOURCES_FAILED = 'GET_SOURCES_FAILED'

export const GET_ARTICLES = 'GET_ARTICLES'
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS'
export const GET_ARTICLES_FAILED = 'GET_ARTICLES_FAILED'

export const ERROR_THROWN = 'ERROR_THROWN'
export const ERROR_CLEAR = 'ERROR_CLEAR'
export const ERROR_RETRY = 'ERROR_RETRY'
