export const GET_SOURCES = 'GET_SOURCES'
export const GET_SOURCES_SUCCESS = 'GET_SOURCES_SUCCESS'
export const GET_SOURCES_FAILED = 'GET_SOURCES_FAILED'

export const GET_ARTICLES = 'GET_ARTICLES'
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS'
export const GET_ARTICLES_FAILED = 'GET_ARTICLES_FAILED'
